services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,app,web
      - DATABASE_NAME=library_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=3456
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 3456
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  static_volume:
  media_volume:
  db_data:
