services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,app,web
      - DATABASE_NAME=library_db
      - DATABASE_USER=alireza
      - DATABASE_PASSWORD=3456
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    depends_on:
      - db
      - rabbitmq

  nginx:
    image: registry.mahbodai.ir/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

  db:
    image: registry.mahbodai.ir/postgis:15-3.5
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: alireza
      POSTGRES_PASSWORD: 3456

    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  geoserver:
    image: registry.mahbodai.ir/geoserver:2.24.2
    ports:
      - "8080:8080"
    volumes:
      - /home/alireza/Desktop/library-project/library/dir_data:/opt/geoserver/dir_data
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=geoserver

  rabbitmq:
    image: registry.mahbodai.ir/rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  celery_worker:
    build:
      context: .
    command: celery -A library worker --loglevel=info
    depends_on:
      - rabbitmq

  celery_beat:
    build:
      context: .
    command: celery -A library beat --loglevel=info
    depends_on:
      - celery_worker
      - rabbitmq

volumes:
  static_volume:
  media_volume:
  db_data:
  geoserver_data:


